### ISSUE TITLE
Context search has incorrect symbol

### ISSUE THREAD

**Issue by Golyshkin** [shmuz/far2m#49] opened 2024-01-25 09:59 UTC
**Pre-Condition:**
1. System has Russian & English installed languages
2. Currently set an ENG mode
3. Opened any folder with existed files

**Test Steps:**
1. Press ALT_LEFT for activate context search in file panel
2. Press **tmp** symbols

Actual Result:
1. first russian symbol is typed as showed on the screen

Expected Result:
1. All symbols SHOULD be according to actual selected language

![image](https://github.com/shmuz/far2m/assets/772340/292c857f-43b8-4899-8473-72557d4749cf)

**Comment by shmuz** [comment] 2024-01-25 10:22
LEFT+ALT should not activate Quick Search. And it doesn't activate it on my machine.
Do you have a macro with `key="AltLeft"` ? If yes then please show me it.

**Comment by Golyshkin** [comment] 2024-01-25 11:03
Yes, you right. AltLeft+Symbols activates a quick search. I meant this one.

**Comment by shmuz** [comment] 2024-01-25 11:08
What key combination is used to switch languages?

**Comment by Golyshkin** [comment] 2024-01-25 11:14
> What key combination is used to switch languages?

SUPER (Window Key) + SPACE

**Comment by shmuz** [comment] 2024-01-25 11:21
My system also has English + Russian.
I go to `/` directory (which has `tmp` subdirectory),
Then I repeat your actions and the problem is not reproduced.

Do you have any macros installed?
It can be checked by selecting  'Macro Browser' from the Plugins Menu (F11)

**Comment by Golyshkin** [comment] 2024-01-25 11:26
![image](https://github.com/shmuz/far2m/assets/772340/f2416384-1722-4bf5-9163-b5b390e661e1)

+ I have some standard macros from far showed below

![image](https://github.com/shmuz/far2m/assets/772340/a18b9bbe-6d01-4219-9184-bfa729c95bca)

**Comment by shmuz** [comment] 2024-01-25 11:31
Please make a ZIP with all your macro-files and attach it here.

**Comment by Golyshkin** [comment] 2024-01-25 11:35
[scripts.zip](https://github.com/shmuz/far2m/files/14051056/scripts.zip)

**Comment by shmuz** [comment] 2024-01-25 11:48
Unfortunately, even when I replace my macros with yours the problem is not reproduced.
If the current language is English I see `tmp` in the quick search window
If the current language is Russian I see `еьз`

What is your operating system name and version?

**Comment by Golyshkin** [comment] 2024-01-25 12:26
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by shmuz** [comment] 2024-01-25 12:51
I've just tried it on Ubuntu 23.10
- with your macros
- with SUPER (Window Key) + SPACE for switching languages

No luck, it is not reproduced.

You may try to collect additional info:
1. how it behaves with far2m in TTY mode (`far2m --tty`)
2. try it on another system if it is possible

**Comment by Golyshkin** [comment] 2024-01-25 13:33
Thnx. I have tried the --tty option and can confirm that issue is not reproduced with this flag. Further, I have analyzed my {{Far2m.desktop}} 

`[Desktop Entry]
Type=Application
Name=far2m
GenericName=far2m
Comment=File and archive manager
Exec=env LC_ALL=ru_RU.UTF-8 GDK_BACKEND=x11 /usr/local/bin/far2m
TryExec=/usr/local/bin/far2m
Terminal=false
Categories=Utility;FileManager;
Icon=far2m
StartupNotify=true`   

and found that issue happened because 
`
Exec=env LC_ALL=ru_RU.UTF-8 GDK_BACKEND=x11 /usr/local/bin/far2m
`
The correct EXEC string is following

`
Exec=/usr/local/bin/far2m
`
The both languages ENG & RUS are working fine. Probably I had added this ENV for FAR2M which had some problems with it.

**Comment by Golyshkin** [comment] 2024-01-25 13:41
Could you test the 
`
Exec=env GDK_BACKEND=x11 /usr/local/bin/far2m
`
I would like to use it and issue can be reproduced!

**Comment by shmuz** [comment] 2024-01-25 13:53
I tested it under Mint 21.2 and Ubuntu 23.10 and verified that under the running far2m `GDK_BACKEND=x11`
The issue is not reproduced.

**Comment by Golyshkin** [comment] 2024-01-25 14:07
Its very strange, on my PC with this ENV 100% reproducible...

**Comment by shmuz** [comment] 2024-01-25 14:12
The problem can be found on the system where the problem exists.
I don't know what I can do if it does not reproduce.

**Comment by Golyshkin** [comment] 2024-01-25 14:19
OK, disabled `GDK_BACKEND=x11` at current moment

**Comment by shmuz** [comment] 2024-01-25 14:22
We may leave this issue open.

**Comment by shmuz** [comment] 2024-02-03 23:31
Closing, with any new data it may be reopened.

**Comment by shmuz** [comment] 2024-02-04 08:28
Need to be tested under Wayland environment.

**Comment by shmuz** [comment] 2024-04-13 21:34
Now I was able to reproduce the issue.
I have 2 keyboards layout defined: English and Russian.
The issue does not exist on my system when English is defined as the 1-st layout.
But when I set Russian as the 1-st layout the issue appeared.
It is probably related to wxWidgets library but upgrading it to version 3.2 did not help.

**Comment by akruphi** [comment] 2024-04-15 11:09
Очень интересно, что протестил в far2l-GUI (под X11) обратную ситуацию: раскладки English (по умолчанию) + Russian. Делаю Alt+ по английской, ловит русскую:
![image](https://github.com/shmuz/far2m/assets/92621645/39723a97-5db7-4aed-af29-a6c34e023fa2)

Фича внутри общего кода с far2l.

**Comment by shmuz** [comment] 2024-04-15 11:40
@akruphi 
Это поведение правильное, соответствует состоянию опции на картинке внизу.

![image](https://github.com/shmuz/far2m/assets/344558/eb41cd6a-a19e-4ce8-afc9-5a71b55ade76)

**Comment by Golyshkin** [comment] 2024-05-08 06:35
> @akruphi Это поведение правильное, соответствует состоянию опции на картинке внизу.
> 
> ![image](https://private-user-images.githubusercontent.com/344558/322465979-9edc78ac-fc13-4fea-b68e-651818ca55ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTAyNzMsIm5iZiI6MTcxNTE0OTk3MywicGF0aCI6Ii8zNDQ1NTgvMzIyNDY1OTc5LTllZGM3OGFjLWZjMTMtNGZlYS1iNjhlLTY1MTgxOGNhNTVlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwNjMyNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03ZTJhYjg3YzE2OWNiNTRiNWYzNGQ1ZWEyZTViMTAxM2VjZTc3MjVlNDA1Mzk3ODI1YTJkNzVmODM0NjlhYjViJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ELay7dBEBkSTQahpykJvM2M4JEE_yfaAkM3XGQUTMy4)

Ага, если ее отключить, то первый символ ВООБЩЕ не ловистся ни русский ни английский...

**Comment by Golyshkin** [comment] 2024-05-16 13:48
> > Ага, если ее отключить, то первый символ ВООБЩЕ не ловистся ни русский ни английский...
> 
> Не могу с этим согласиться. Сейчас произвёл проверку на Ubuntu 22.04.

А у меня, как всегда, 100% reproducibility...

**Comment by shmuz** [comment] 2024-11-11 21:53
@Golyshkin 
Не так давно был коммит, влияющий на отображение символов при Fast Find.
Возможно ваша проблема при этом разрешилась, имеет смысл проверить.

**Comment by Golyshkin** [comment] 2024-12-05 16:43
> @Golyshkin Не так давно был коммит, влияющий на отображение символов при Fast Find. Возможно ваша проблема при этом разрешилась, имеет смысл проверить.

Привет,  да, вроде пофиксилось на `version 2.6.0-2024-11-18-990b283e-beta Linux x86_64`

Осталось еще пофиксить NUM клавиши если запускаемся через Wayland. На X11 не воспроизводится если запускать через

`Exec=env LC_ALL=ru_RU.UTF-8 GDK_BACKEND=x11 /usr/local/bin/far2m`

**Closed** 2024-12-05 19:02 UTC

**Comment by Golyshkin** [comment] 2024-12-09 16:19
> Если пофиксилось, то закрываю.
> 
> > Осталось еще пофиксить NUM клавиши если запускаемся через Wayland.
> 
> Вы имеете в виду #51 ? Так я же там указал причину - проблема в версии 3.0 библиотеки wxGTK. На версии 3.2 проблемы нет. Там же я привёл команды для бэкпортирования wxGTK 3.2 в Ubuntu 22.04. Я тогда реально сделал это на своей Ubuntu 22.04, и проблема ушла.

Да, обновил тикет #51, появились другие проблемы, но решились. Спасибо!
